[theme]
base            = "dark"
backgroundColor          = "#05050b"
secondaryBackgroundColor = "#0d0d18"
textColor                = "#e8eaf6"
primaryColor             = "#00e5a0"
font                     = "monospace"

[server]
port        = 8501
headless    = true
runOnSave   = false

[browser]
gatherUsageStats = false
